#default
server:
  port: 7002

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: middle-service
  redis:
    host: 127.0.0.1
    port: 6379



eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/





