server:
  port: 7000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: web-service
          uri: lb://WEB-SERVICE
          predicates:
            - Path=/tagWeb/**
        - id: middle-service
          uri: lb://MIDDLE-SERVICE
          predicates:
            - Path=/middle-service/**



