server:
  port: 7000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: web-service
          uri: http://localhost:7001/
          predicates:
            - Path=/tagWeb/**
        - id: middle-service
          uri: http://localhost:7002/
          predicates:
            - Path=/middle-service/**



